---
- hosts: localhost
  connection: local

  tasks:
  - name: Create a 3 EC2 instance where 2 are ubuntu distribution and 1 is AWS Linux
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "mumbai-keypair"
      instance_type: t2.micro
      security_group: "sg-04912ee300ca3f133"
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined  
      network_interfaces:
        - assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        Environment: "{{ item.name }}"
    loop:
      - { image: "ami-0e1d06225679bc1c5", name: "manage-node-1" } 
      - { image: "ami-0f58b397bc5c1f2e8", name: "manage-node-2" } 
      - { image: "ami-0f58b397bc5c1f2e8", name: "manage-node-3" }